version: '3.8'

services:
  blablalink-bot:
    image: ghcr.io/lo2495/daily-task-automator:latest 
    container_name: blablalink-bot
    restart: no
    env_file:
      - .env
    shm_size: '2gb'
    volumes:
      - ./cookies.json:/app/cookies.json 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true          
      - WATCHTOWER_POLL_INTERVAL=86400   
      - WATCHTOWER_LABEL_ENABLE=true  